name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install clang-format-20
      run: sudo apt-get update && sudo apt-get install -y clang-format-20
    - name: Install dependencies
      run: sudo apt-get install -y libsodium-dev libseccomp-dev libcap-dev
    - name: make
      run: make CLANG_CFI=y
    - name: make test
      run: make CLANG_CFI=y test
    - name: make with GCC
      run: make clean && make CC=gcc
    - name: make with NO_SANDBOX=y
      run: make clean && make NO_SANDBOX=y
    - name: make install
      run: sudo make install
